spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-out:
          destination: greetings
          contentType: application/json
  application:
    name: kafka-producer

server:
  port: 0

eureka.instance.instance-id: ${spring.application.name}.${random.value}